### ISSUE TITLE
[Stardew Symphony] Periodic SMAPI console errors

### ISSUE THREAD

**Issue by plasticpal** [janavarro95/Stardew_Valley_Mods#44] opened 2018-11-08 22:53 UTC
```
[17:36:34 ERROR Stardew Symphony Remastered] This mod failed in the MenuEvents.MenuClosed event. Technical details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at StardewSymphonyRemastered.Framework.MusicManager.checkGenericMusic(String songListKey) in C:\Users\owner\Documents\Visual Studio 2015\Projects\github\StardewValleyMods\GeneralMods\StardewSymphonyRemastered\StardewSymphonyRemastered\Framework\Music\MusicManager.cs:line 615
   at StardewSymphonyRemastered.Framework.MusicManager.selectMusic(String songListKey) in C:\Users\owner\Documents\Visual Studio 2015\Projects\github\StardewValleyMods\GeneralMods\StardewSymphonyRemastered\StardewSymphonyRemastered\Framework\Music\MusicManager.cs:line 471
   at StardewSymphonyRemastered.StardewSymphony.MenuEvents_MenuClosed(Object sender, EventArgsClickableMenuClosed e) in C:\Users\owner\Documents\Visual Studio 2015\Projects\github\StardewValleyMods\GeneralMods\StardewSymphonyRemastered\StardewSymphonyRemastered\StardewSymphony.cs:line 191
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 62
```

Full log: https://log.smapi.io/EFv3dB0a

**Comment by janavarro95** [comment] 2018-12-10 09:38
Fixed in most recent Development branch update likely caused by Stardust Core becoming outdated.

**Closed by janavarro95** 2018-12-10 09:38 UTC
