### ISSUE TITLE
SaveAnywhere: compability issue, only work once, animation stuck,

### ISSUE THREAD

**Issue by IdaeroAce** [janavarro95/Stardew_Valley_Mods#15] opened 2017-07-29 08:14 UTC
I already posted this to Nexus... So I made some test to find some bugs because it seems people are lazy to troubleshoot things. Note that my Englist are sukcz so g3t rreddy 2 confused. Here there are:

1. This mod is not compatible with CJB Cheat Menu. 
Warping won't work, and cutscene/cinematic/special dialog will be bugged (camera will more somewhere to cliff, sometimes also the player, can't move or open menu, must alt-f4)

2. This mod is not compatible with Part of the Community mod. 
It will corrupt save data (open the save data with Notepad and see the save data will be only till Location-CommunityCenter). Or maybe this is Part of the Community mod's bug?

3. Save Anywhere can be used once a day (in game),... 
other wise, when you load, the npc will freeze, and sometimes moved to unwalkable place. For example, on 15 Summer 10AM, I save the game then quit. Then, when I play again, on 15 Summer 5PM, I save the game and quit. So then next time I load it, the NPC will stuck, and sometimes get to weird place.

4. (someone else already mentioned this) Save Anywhere not saving locations on normal save
So if you use normal save, then quit, next time you load it you will warped to last time you save with Save Anywhere (press K), and also the time. If you did this, you only need to delete the mod Save data again.

5. Player warping will only triggered if the player move. This is not really a problem since everyone must be already move from bed anyway.

6. Possible animation glitch after load.
Right after load, when still in bed, if the player do an animation (for example use Watering Can), then move (to trigger player warp), the player animation will be bugged (it play Watering animation, looping) and can't do interaction (still can walk around)

7. Warping will only work once in game season. 
I mean, if you have load the game, then quit to menu, then load again, you won't get warped (and i think the npc too, and also the time wont change)

8. If you have 2 (or more) profiles before you use SaveAnywhere mod, and then you install the mod and load on a profile (example John), then use the SaveAnywhere. And then you quit the game, and and start the game again, load on another profile (example Ignis), you will get warped to John's location, also the NPC are warped based on John's save, and also the time.

I already test the mod with some other mods: AllProfessions, BetterRNG, CalendarAnywhere, CJBItemSpawner, CJBShowItemSellPrice, DurableFences, FishingOverhaul, GetDressed, GiftTasteHelpes, HealthBars, JunimoDepositAnywhere, NPCMapLocations, SMAPISprinkleMod, and the default TrainerMod. All works well. Haven't test with StardewValleyMP.

So it seems most people that got "Warping not work bug" and "Cinematic glitch freeze" most likely because they use CJBCheatMenu (pfft.. cheater XD). And why use SaveAnywhere if you can warp everywhere, get free money, move really fast, get full reletionship instant, water all crop instant, etc? LMAO

**Comment by Pathoschild** [comment] 2017-08-06 04:30
@IdaeroAce Thanks for testing! These should be fixed in the recent refactoring (see #14, #16, #17, and #22). If any of these still happens in 2.5, please open a new ticket for each issue.

* **Not compatible with CJB Cheats Menu (warping / cutscenes broken)**
   Can't reproduce, seems to be fixed.

* **Not compatible with Part of the Community (save corruption)**
  Can't reproduce, seems to be fixed.

* **Save Anywhere can only be used once per day (errors after loading)**
  Can't reproduce, seems to be fixed.

* **Saving via sleep doesn't clear non-sleep save data.**
  Fixed.

* **Player warp only triggers when the player moves.**
   Fixed.

* **Animation glitch after load.**
   Fixed (you warp before moving now).

* **Warping only works once per game session.**
   Fixed.

* **If two players have the same name, their data conflicts.**
   The save system has been rewritten, and I don't think this should happen anymore.

**Closed** 2017-08-06 05:00 UTC
